
export const content = {
  fr: {
    nav: {
      home: 'Accueil',
      portfolio: 'Portfolio',
      about: 'À propos',
      contact: 'Contact',
      visualizer: 'Visualiseur',
    },
    home: {
      title: 'Artiste 3D &<br />Développeur',
      subtitle: 'Créateur d\'expériences numériques immersives en Vaucluse',
      intro_paragraph: 'Basé dans le Vaucluse, j\'allie ma passion pour la création 3D et mon expertise en développement pour concevoir des solutions innovantes : applications web, visites virtuelles, configurateurs 3D interactifs, etc.',
      hero_cta: 'Découvrir mes projets',
      three_placeholder: 'Placeholder pour un élément 3D interactif',
      stats: {
          projects: 'Projets réalisés',
          experience: 'Années d\'expérience',
          expertise: 'Domaines d\'expertise',
          technologies: 'Technologies maîtrisées',
      },
      presentation: {
          part1: 'Profil hybride, je fusionne',
          highlight1: 'design 3D',
          highlight2: 'développement interactif',
          part2: 'et',
          highlight3: 'développement web',
          part3: 'pour créer des expériences numériques uniques et engageantes.',
      },
      services: {
          title: 'Mes domaines d\'activité',
          item1: { title: 'Infographie 3D', description: 'Modélisation, texturing et animation pour l\'architecture, l\'ingénierie et la communication visuelle.' },
          item2: { title: 'Développement 3D Interactif', description: 'Création d\'expériences immersives (VR, AR, mixte), de configurateurs produits et de visites virtuelles sur Unity et Unreal Engine.' },
          item3: { title: 'Développement Web', description: 'Conception d\'applications (React, Angular), de backends (PHP), de sites WordPress et optimisation SEO.' },
      },
      showreel: {
          title: 'Donner vie aux idées.',
          subtitle: 'Un aperçu de mon travail en mouvement.',
          cta: 'Voir mes projets',
      },
      skills: {
          title: 'Compétences & outils',
          cta: 'Découvrir toutes mes compétences',
      },
      cta: {
          title: 'Prêt à collaborer ?',
          subtitle: 'Je suis prêt à mettre mes compétences au service de vos projets. Discutons de la manière dont je peux intégrer votre équipe.',
          button: 'Me contacter',
      }
    },
    portfolio: {
      title: 'Mes projets',
      intro: {
        part1: 'Voici une sélection de mes travaux, illustrant l\'étendue de mes compétences : de la ',
        highlight1: 'création visuelle en 3D',
        part2: ' jusqu\'au développement d\'',
        highlight2: 'applications interactives',
        part3: ' et de ',
        highlight3: 'sites web performants',
        part4: '.',
      },
      filter_all_projects: 'Tous les projets',
      filter_visualizable_projects: 'Projets 3D Visualisables',
      layout_grid: 'Grille',
      layout_list: 'Liste',
      new_badge: 'Nouveau',
      view_project_cta: 'Voir le projet',
      search_placeholder: 'Rechercher un projet...',
      sort_label: 'Trier par',
      sort_newest: 'Plus récents',
      sort_oldest: 'Plus anciens',
      no_results: 'Aucun projet ne correspond à votre recherche.',
      back_to_portfolio: 'Retour au portfolio',
      interactive_experience_title: 'Expérience interactive',
      visualize_3d_cta: 'Visualiser en 3D',
      gallery_title: 'Galerie',
      other_projects_title: 'Autres projets',
      modal_technologies: 'Technologies utilisées',
      modal_close: 'Fermer',
    },
    about: {
      title: 'À propos de moi',
      profile_title: 'Profil',
      profile_content: "Je m'appelle Donovan Chartrain, et je suis un créateur numérique passionné par l'interactivité et la 3D, basé dans le Vaucluse. En recherche active d'un poste dans la région (Vaucluse, Gard), j'aime concevoir des expériences qui allient technologie et sens. Mon but est de donner vie à des sites web, des applications interactives ou des animations 3D qui marquent les esprits.",
      journey_title: 'Mon parcours',
      journey_content: "Mon chemin a commencé par un Bac Pro en maintenance industrielle, où j'ai appris à comprendre les systèmes techniques et à résoudre des problèmes concrets. C'est cette base solide, ancrée dans le réel, qui m'a permis de développer une approche pragmatique de la création numérique. Au fil des années, j'ai travaillé dans des environnements très différents : agence de communication, bureaux d'études, maîtrise d'ouvrage, puis cabinet d'ingénierie. Chacune de ces expériences a forgé une nouvelle facette de mon métier : la rigueur, la créativité, la communication, et surtout, la capacité à vulgariser des sujets techniques. Aujourd'hui, elles me permettent d'avoir une vision transversale, de passer d'un univers à un autre avec souplesse, et de proposer des solutions complètes, à la fois techniques et humaines.",
      skills_title: 'Compétences',
      experience_title: 'Parcours',
      education_title: 'Formations',
      timeline: [
        {
          type: 'formation',
          role: 'BEP & BAC PRO Maintenance des équipements industriels',
          company: 'Lycée François Rabelais, Fontenay-le-Comte',
          period: '2013 – 2015',
          description: '',
          date: '2013-09-01',
        },
        {
          type: 'experience',
          role: 'Infographiste 3D Junior',
          company: 'COM3D, Pérols (34)',
          period: '2015 – 2016',
          description: '• Rendu photoréaliste et animation marketing.\n• Traitement de fichiers CAO pour visualisations 3D.',
          date: '2015-09-01',
        },
        {
          type: 'formation',
          role: 'Modeleur BIM',
          company: 'AFPA Nîmes',
          period: '2020',
          description: '',
          date: '2020-01-01',
        },
        {
          type: 'experience',
          role: 'Dessinateur Projeteur',
          company: 'MB CONCEPTION, Pouzauges (85)',
          period: 'Mars – Mai 2021',
          description: '• Modélisation BIM pour projets architecturaux.',
          date: '2021-03-01',
        },
        {
          type: 'experience',
          role: 'Infographiste 3D / Développeur Unity',
          company: 'POLYNOTES, Meylan (38)',
          period: 'Mai – Octobre 2021',
          description: "• Développement de scènes interactives sous Unity.\n• Création de visuels et d'animations 3D.",
          date: '2021-05-01',
        },
        {
          type: 'experience',
          role: 'Infographiste 3D',
          company: 'Grapheau, Saint-Pierre-de-Vassols (84)',
          period: 'Septembre 2022 – Avril 2024',
          description: "• Création d'animations et de visuels 3D.\n• Développement d'applications 3D interactives.\n• Recherche et développement pour optimiser les outils internes.",
          date: '2022-09-01',
        },
        {
          type: 'formation',
          role: 'Formation SEO/SEA',
          company: 'Financée par Grapheau',
          period: '2024',
          description: '',
          date: '2024-01-01',
        },
        {
          type: 'experience',
          role: 'Développeur Informatique',
          company: 'Grapheau, Saint-Pierre-de-Vassols (84)',
          period: 'Avril 2024 - Juillet 2025',
          description: "• Développement d'outils internes et d'applications interactives.\n• Optimisation et structuration des bases de données.\n• Intégration de solutions SEO/SEA pour améliorer la visibilité web.",
          date: '2024-04-01',
        },
      ],
      resume_cta: 'Télécharger mon CV',
      resume_section_title: 'Télécharger mon CV',
      resume_section_subtitle: 'Choisissez la version qui correspond le mieux à vos besoins. La version designer est idéale pour une consultation numérique, tandis que la version imprimable est optimisée pour une lecture en noir et blanc.',
      resume_designer_title: 'Version Designer',
      resume_designer_description: 'Une version visuellement riche, parfaite pour une consultation sur écran.',
      resume_printable_title: 'Version Imprimable',
      resume_printable_description: 'Une version sobre et optimisée pour une impression en noir et blanc.',
      resume_download_button: 'Télécharger la version sélectionnée',
      resume_error_title: 'Aucune version sélectionnée',
      resume_error_description: 'Veuillez choisir une version du CV à télécharger.',
    },
    contact: {
      title: 'Contact',
      subtitle: 'Je suis actuellement à la recherche de nouvelles opportunités professionnelles dans le Vaucluse, le Gard et leurs alentours. N\'hésitez pas à me contacter pour discuter d\'un futur poste.',
      form_title: 'Envoyez-moi un message',
      form_name: 'Nom',
      form_name_placeholder: 'Votre nom complet',
      form_email: 'Email',
      form_email_placeholder: 'votre@email.com',
      form_company: 'Nom de l\'entreprise (Optionnel)',
      form_company_placeholder: 'Nom de votre entreprise',
      form_phone: 'Téléphone (Optionnel)',
      form_phone_placeholder: '+33 6 00 00 00 00',
      form_message: 'Message',
      form_message_placeholder: 'Vous pouvez rédiger votre message ici.',
      form_submit: 'Envoyer',
      form_sending: 'Envoi en cours...',
      form_success_title: 'Message envoyé !',
      form_success: 'Merci de m\'avoir contacté. Je vous répondrai dans les plus brefs délais.',
      form_error_title: 'Erreur',
      form_error: 'Une erreur est survenue. Veuillez réessayer.',
      info_title: 'Informations de contact',
      info_email_label: 'Email',
      info_phone_label: 'Téléphone',
      info_location_label: 'Localisation',
      social_title: 'Restons connectés',
      social_subtitle: 'Suivez-moi pour voir l\'évolution de mes projets et de nouvelles créations.',
      availability_title: 'Ouvert aux opportunités',
      availability_text: 'Réponse garantie sous 24 heures.',
    },
    style_guide: {
      title: 'Charte Graphique',
      subtitle: "Les principes, les composants et les styles qui définissent l'identité visuelle de ce portfolio.",
      logo_title: 'Logo',
      logo_description: "Le logo est le point central de l'identité. Il est utilisé dans la navigation principale et le preloader.",
      colors_main_title: 'Palette de Couleurs - Site Principal',
      colors_main_description: "La palette principale est conçue pour être sobre, professionnelle et mettre en valeur le contenu visuel. Elle s'articule autour d'un fond très sombre, rehaussé par une couleur primaire vive et technologique.",
      colors_visualizer_title: 'Palette de Couleurs - Visualiseur 3D',
      colors_visualizer_description: "La palette du visualiseur est plus simple pour ne pas distraire de l'objet 3D. Le bleu électrique sert de couleur d'action pour les contrôles.",
      typography_title: 'Typographie',
      typography_description: "La police 'Space Grotesk' est utilisée pour tous les textes, offrant un aspect moderne et technique. La hiérarchie est claire pour garantir la lisibilité.",
      h1_sample: 'Artiste 3D & Développeur',
      h2_sample: 'Mes Domaines d\'Activité',
      h3_sample: 'Infographie 3D',
      body_sample: 'Alliant ma passion pour la création 3D et mon expertise en développement d\'applications web et interactives, je conçois des solutions visuelles innovantes.',
      label_sample: 'Voir le projet',
      components_title: 'Composants et Interactivité',
      components_description: "Les composants suivent une logique de design cohérente : les éléments structurels comme les cartes ont des coins droits pour la stabilité, tandis que les éléments interactifs comme les boutons ont des coins arrondis pour inviter à l'action.",
      buttons_title: 'Boutons',
      button_primary: 'Bouton Primaire',
      button_secondary: 'Bouton Secondaire',
      button_outline: 'Bouton Contour',
      button_ghost: 'Bouton Fantôme',
      badges_title: 'Badges',
      badge_default: 'Badge Défaut',
      badge_secondary: 'Badge Secondaire',
      badge_outline: 'Badge Contour',
      badge_sector: 'Secteur',
      cards_title: 'Cartes',
      card_standard_title: 'Carte Standard',
      card_standard_description: "Utilisée pour structurer le contenu. Coins droits pour un aspect stable et ordonné.",
      card_highlight_title: 'Carte Mise en Avant',
      card_highlight_description: "Une bordure et une ombre de couleur primaire sont utilisées pour attirer l'attention.",
      cta_title: "Intéressé par mon approche du design ?",
      cta_subtitle: "Discutons de la manière dont cette rigueur et cette créativité pourraient s'appliquer à vos projets.",
      cta_button: "Me contacter"
    },
    legal_notice: {
        title: "Mentions Légales",
        editor_title: "1. Éditeur du site",
        editor_name: "Nom & Prénom",
        editor_address: "Adresse",
        editor_email: "Email",
        editor_phone: "Téléphone",
        hosting_title: "2. Hébergement",
        hosting_content: "Le site est hébergé par [Nom de l'hébergeur], dont le siège social est situé à [Adresse de l'hébergeur] et joignable au [Numéro de téléphone de l'hébergeur].",
        ip_title: "3. Propriété intellectuelle",
        ip_content1: "L'ensemble de ce site relève de la législation française et internationale sur le droit d'auteur et la propriété intellectuelle. Tous les droits de reproduction sont réservés, y compris pour les documents téléchargeables et les représentations iconographiques et photographiques.",
        ip_content2: "La reproduction de tout ou partie de ce site sur un support électronique quel qu'il soit est formellement interdite sauf autorisation expresse du directeur de la publication.",
        data_title: "4. Données personnelles",
        data_content: "Les informations recueillies via le formulaire de contact sont nécessaires pour répondre à votre demande. Elles sont destinées uniquement à Chartrain Donovan et ne seront pas transmises à des tiers. Conformément à la loi \"informatique et libertés\" du 6 janvier 1978 modifiée, vous bénéficiez d’un droit d’accès, de rectification et de suppression des informations qui vous concernent.",
    },
    privacy_policy: {
      title: "Politique de Confidentialité",
      introduction_title: "Introduction",
      introduction_content: "Cette politique de confidentialité a pour objectif de vous informer sur la manière dont vos informations personnelles sont collectées et traitées sur ce site. Je m'engage à protéger votre vie privée et à garantir que vos données personnelles sont traitées de manière transparente et sécurisée.",
      collection_title: "Collecte des données personnelles",
      collection_content: "Ce site collecte des données de deux manières : les données que vous me fournissez directement et les données collectées automatiquement par des services tiers.",
      user_data_title: "Données fournies par l'utilisateur",
      user_data_content: "Les seules données personnelles que je collecte directement sont celles que vous me fournissez volontairement via le formulaire de contact. Ces données incluent :",
      user_data_list: ["Votre nom", "Votre adresse e-mail", "Le nom de votre entreprise (facultatif)", "Votre numéro de téléphone (facultatif)", "Le contenu de votre message"],
      third_party_data_title: "Données collectées automatiquement et par des tiers",
      third_party_data_content: "Pour fonctionner et vous offrir une expérience enrichie, ce site s'appuie sur des services tiers qui peuvent collecter des données et déposer des cookies :",
      third_party_hosting: "<strong>Hébergement (Vercel) :</strong> Le site est hébergé par Vercel. Vercel peut collecter des données d'analyse anonymes (telles que le nombre de visiteurs, les pages visitées, le pays d'origine) pour mesurer les performances et la sécurité du site. Ces données ne permettent pas de vous identifier personnellement.",
      third_party_youtube: "<strong>Contenu embarqué (YouTube) :</strong> Les vidéos intégrées sur ce site sont hébergées sur YouTube. Lorsque vous chargez une page contenant une vidéo, YouTube (détenu par Google) peut déposer des cookies sur votre navigateur pour suivre votre interaction avec la vidéo, même si vous ne la lisez pas. Nous utilisons le mode de confidentialité avancée de YouTube (`youtube-nocookie.com`) pour limiter cette collecte, qui ne s'active en principe qu'au moment de la lecture de la vidéo.",
      third_party_responsibility: "Il est de votre responsabilité de consulter les politiques de confidentialité de ces services tiers pour plus d'informations.",
      usage_title: "Utilisation des données",
      usage_content: "Les informations que vous fournissez via le formulaire sont utilisées exclusivement pour :",
      usage_list: ["Répondre à vos demandes de contact et à vos questions.", "Communiquer avec vous concernant d'éventuelles opportunités de collaboration ou de projet."],
      usage_share: "Vos données personnelles directes ne seront jamais vendues, partagées ou louées à des tiers sans votre consentement explicite.",
      retention_title: "Durée de conservation des données",
      retention_content: "Vos données personnelles issues du formulaire de contact sont conservées pour la durée nécessaire au traitement de votre demande et à la gestion de notre relation professionnelle. Si aucune collaboration n'est entamée, vos données seront supprimées dans un délai raisonnable.",
      rights_title: "Vos droits",
      rights_content: "Conformément à la réglementation en vigueur (notamment le RGPD), vous disposez des droits suivants concernant vos données personnelles :",
      rights_list: ["Droit d'accès", "Droit de rectification", "Droit à l'effacement (droit à l'oubli)", "Droit à la limitation du traitement", "Droit à la portabilité des données"],
      rights_exercise: "Pour exercer ces droits sur les données que je collecte directement, vous pouvez me contacter à l'adresse e-mail indiquée dans les mentions légales. Pour les données collectées par les services tiers, vous devez exercer vos droits directement auprès d'eux.",
      security_title: "Sécurité",
      security_content: "Je mets en œuvre les mesures techniques et organisationnelles appropriées pour garantir la sécurité de vos données personnelles et les protéger contre toute perte, destruction, altération ou accès non autorisé.",
      modifications_title: "Modifications de la politique de confidentialité",
      modifications_content: "Je me réserve le droit de modifier cette politique de confidentialité à tout moment. Les modifications seront publiées sur cette page.",
    },
    visualizer: {
      header_back: 'Retourner au site',
      header_home_breadcrumb: 'Espace Visualiseur',
      header_library_breadcrumb: 'Bibliothèque',
      home_title: 'Espace Visualiseur 3D',
      home_subtitle: "Bienvenue dans l'espace interactif. Ici, vous pouvez manipuler, explorer et examiner en détail une sélection de mes modèles 3D directement dans votre navigateur.",
      home_cta_library: 'Explorer la bibliothèque',
      home_cta_portfolio: 'Retourner au portfolio',
      home_cta_contact_title: 'Un projet en tête ?',
      home_cta_contact_subtitle: 'Discutons de la manière dont nous pourrions concrétiser votre vision. Je suis ouvert à de nouvelles collaborations.',
      home_cta_contact_button: 'Me contacter',
      library_title: 'Bibliothèque des modèles',
      library_subtitle: 'Explorez, manipulez et examinez tous les modèles 3D disponibles.',
      library_loading: 'Chargement des modèles...',
      library_empty: 'Aucun modèle 3D disponible pour le moment.',
      item_card_badge: '3D',
      item_card_cta: 'Voir le modèle',
      item_detail_loading: 'Chargement du visualiseur...',
      item_detail_not_found: 'Modèle non trouvé',
      item_detail_not_found_message: 'Impossible de trouver les informations pour ce modèle.',
      item_detail_no_model: 'Aucun modèle 3D disponible pour cet objet.',
      item_detail_cta_project: 'Voir le projet',
      item_detail_cta_library: 'Retour à la bibliothèque',
      canvas_loading: 'Chargement du modèle 3D...',
      help_close: "Fermer l'aide",
      help_title: 'Contrôles de la caméra',
      help_mouse_title: 'Souris',
      help_mouse_rotate: 'Clic Gauche + Glisser',
      help_mouse_rotate_desc: 'Rotation',
      help_mouse_pan: 'Clic Droit + Glisser',
      help_mouse_pan_desc: 'Déplacement',
      help_mouse_zoom: 'Molette',
      help_mouse_zoom_desc: 'Zoom',
      help_touch_title: 'Tactile',
      help_touch_rotate: '1 Doigt + Glisser',
      help_touch_rotate_desc: 'Rotation',
      help_touch_zoom: '2 Doigts + Pincer',
      help_touch_zoom_desc: 'Zoom',
      help_touch_pan: '2 Doigts + Glisser',
      help_touch_pan_desc: 'Déplacement',
      help_button_title: "Afficher l'aide",
      reset_button_title: 'Réinitialiser la vue',
      autorotate_button_title_pause: 'Mettre en pause',
      autorotate_button_title_play: 'Reprendre la rotation',
      fullscreen_button_title_exit: 'Quitter le mode plein écran',
      fullscreen_button_title_enter: 'Passer en mode plein écran',
    },
  },
  en: {
    nav: {
      home: 'Home',
      portfolio: 'Portfolio',
      about: 'About',
      contact: 'Contact',
      visualizer: '3D viewer',
    },
    home: {
      title: '3D Artist &<br />Developer',
      subtitle: 'Creator of immersive digital experiences in Vaucluse, France',
      intro_paragraph: 'Based in the Vaucluse area (France), I combine my passion for 3D creation with my development expertise to design innovative solutions: web applications, virtual tours, interactive 3D configurators, and more.',
      hero_cta: 'Discover my projects',
      three_placeholder: 'Placeholder for an interactive 3D element',
       stats: {
          projects: 'Projects completed',
          experience: 'Years of experience',
          expertise: 'Areas of expertise',
          technologies: 'Technologies mastered',
      },
      presentation: {
          part1: 'Hybrid profile, I merge',
          highlight1: '3D design',
          highlight2: 'interactive development',
          part2: 'and',
          highlight3: 'web development',
          part3: 'to create unique and engaging digital experiences.',
      },
      services: {
          title: 'My fields of activity',
          item1: { title: '3D Graphics', description: 'Modeling, texturing, and animation for architecture, engineering, and visual communication.' },
          item2: { title: 'Interactive 3D Development', description: 'Creation of immersive experiences (VR, AR, mixed reality), product configurators, and virtual tours on Unity and Unreal Engine.' },
          item3: { title: 'Web Development', description: 'Design of applications (React, Angular), backends (PHP), WordPress sites, and SEO optimization.' },
      },
      showreel: {
          title: 'Bringing ideas to life.',
          subtitle: 'A glimpse of my work in motion.',
          cta: 'See my projects',
      },
      skills: {
          title: 'Skills & tools',
          cta: 'Discover all my skills',
      },
      cta: {
          title: 'Ready to collaborate?',
          subtitle: 'I am ready to put my skills at the service of your projects. Let\'s discuss how I can join your team.',
          button: 'Contact me',
      }
    },
    portfolio: {
      title: 'My projects',
      intro: {
        part1: 'Here is a selection of my work, illustrating the breadth of my skills: from ',
        highlight1: '3D visual creation',
        part2: ' to the development of ',
        highlight2: 'interactive applications',
        part3: ' and ',
        highlight3: 'high-performance websites',
        part4: '.',
      },
      filter_all_projects: 'All Projects',
      filter_visualizable_projects: 'Viewable 3D Projects',
      layout_grid: 'Grid',
      layout_list: 'List',
      new_badge: 'New',
      view_project_cta: 'View Project',
      search_placeholder: 'Search for a project...',
      sort_label: 'Sort by',
      sort_newest: 'Newest',
      sort_oldest: 'Oldest',
      no_results: 'No projects match your search.',
      back_to_portfolio: 'Back to portfolio',
      interactive_experience_title: 'Interactive Experience',
      visualize_3d_cta: 'Visualize in 3D',
      gallery_title: 'Gallery',
      other_projects_title: 'Other Projects',
      modal_technologies: 'Technologies used',
      modal_close: 'Close',
    },
    about: {
      title: 'About me',
      profile_title: 'Profile',
      profile_content: "My name is Donovan Chartrain, and I am a digital creator passionate about interactivity and 3D, based in the Vaucluse area of France. I am actively looking for a position in the region (Vaucluse, Gard) and enjoy designing experiences that blend technology with meaning. My goal is to bring to life websites, interactive applications, or 3D animations that make a lasting impression.",
      journey_title: 'My Journey',
      journey_content: "My path began with a vocational degree in industrial maintenance, where I learned to understand technical systems and solve concrete problems. It is this solid, reality-based foundation that has allowed me to develop a pragmatic approach to digital creation. Over the years, I have worked in very different environments: a communication agency, design offices, project management, and then an engineering firm. Each of these experiences has forged a new facet of my profession: rigor, creativity, communication, and above all, the ability to simplify technical subjects. Today, they allow me to have a cross-functional vision, to move from one world to another with flexibility, and to offer complete solutions that are both technical and human.",
      skills_title: 'Skills',
      experience_title: 'Journey',
      education_title: 'Education',
      timeline: [
        {
          type: 'formation',
          role: 'Vocational Degree in Industrial Equipment Maintenance',
          company: 'Lycée François Rabelais, Fontenay-le-Comte',
          period: '2013 – 2015',
          description: '',
          date: '2013-09-01',
        },
        {
          type: 'experience',
          role: 'Junior 3D Artist',
          company: 'COM3D, Pérols (34)',
          period: '2015 – 2016',
          description: '• Photorealistic rendering and marketing animation.\n• Processing of CAD files for 3D visualizations.',
          date: '2015-09-01',
        },
        {
          type: 'formation',
          role: 'BIM Modeler',
          company: 'AFPA Nîmes',
          period: '2020',
          description: '',
          date: '2020-01-01',
        },
        {
          type: 'experience',
          role: 'Draftsman/Designer',
          company: 'MB CONCEPTION, Pouzauges (85)',
          period: 'March – May 2021',
          description: '• BIM modeling for architectural projects.',
          date: '2021-03-01',
        },
        {
          type: 'experience',
          role: '3D Artist / Unity Developer',
          company: 'POLYNOTES, Meylan (38)',
          period: 'May – October 2021',
          description: "• Development of interactive scenes in Unity.\n• Creation of 3D visuals and animations.",
          date: '2021-05-01',
        },
        {
          type: 'experience',
          role: '3D Artist',
          company: 'Grapheau, Saint-Pierre-de-Vassols (84)',
          period: 'September 2022 – April 2024',
          description: "• Creation of 3D animations and visuals.\n• Development of interactive 3D applications.\n• Research and development to optimize internal tools.",
          date: '2022-09-01',
        },
        {
          type: 'formation',
          role: 'SEO/SEA Training',
          company: 'Funded by Grapheau',
          period: '2024',
          description: '',
          date: '2024-01-01',
        },
        {
          type: 'experience',
          role: 'IT Developer',
          company: 'Grapheau, Saint-Pierre-de-Vassols (84)',
          period: 'April 2024 - July 2025',
          description: "• Development of internal tools and interactive applications.\n• Database optimization and structuring.\n• Integration of SEO/SEA solutions to improve web visibility.",
          date: '2024-04-01',
        },
      ],
      resume_cta: 'Download my Resume',
      resume_section_title: 'Download my Resume',
      resume_section_subtitle: 'Choose the version that best suits your needs. The designer version is ideal for digital viewing, while the printable version is optimized for black and white reading.',
      resume_designer_title: 'Designer Version',
      resume_designer_description: 'A visually rich version, perfect for on-screen viewing.',
      resume_printable_title: 'Printable Version',
      resume_printable_description: 'A clean version optimized for black and white printing.',
      resume_download_button: 'Download selected version',
      resume_error_title: 'No version selected',
      resume_error_description: 'Please select a CV version to download.',
    },
    contact: {
      title: 'Contact',
      subtitle: 'I am currently seeking new professional opportunities in the Vaucluse, Gard, and surrounding areas. Please feel free to contact me to discuss a future position.',
      form_title: 'Send me a message',
      form_name: 'Name',
      form_name_placeholder: 'Your full name',
      form_email: 'Email',
      form_email_placeholder: 'your@email.com',
      form_company: 'Company Name (Optional)',
      form_company_placeholder: 'Your company\'s name',
      form_phone: 'Phone Number (Optional)',
      form_phone_placeholder: '+1 (555) 000-0000',
      form_message: 'Message',
      form_message_placeholder: 'You can write your message here.',
      form_submit: 'Send',
      form_sending: 'Sending...',
      form_success_title: 'Message sent!',
      form_success: 'Thank you for contacting me. I will get back to you as soon as possible.',
      form_error_title: 'Error',
      form_error: 'An error occurred. Please try again.',
      info_title: 'Contact information',
      info_email_label: 'Email',
      info_phone_label: 'Phone',
      info_location_label: 'Location',
      social_title: 'Let\'s connect',
      social_subtitle: 'Follow me to see my projects evolve and discover new creations.',
      availability_title: 'Open to opportunities',
      availability_text: 'Guaranteed response within 24 hours.',
    },
    style_guide: {
      title: 'Style Guide',
      subtitle: "The principles, components, and styles that define this portfolio's visual identity.",
      logo_title: 'Logo',
      logo_description: 'The logo is the focal point of the identity. It is used in the main navigation and the preloader.',
      colors_main_title: 'Color Palette - Main Site',
      colors_main_description: 'The main palette is designed to be sober, professional, and to highlight visual content. It is based on a very dark background, enhanced by a bright and technological primary color.',
      colors_visualizer_title: 'Color Palette - 3D Visualizer',
      colors_visualizer_description: "The visualizer's palette is simpler to avoid distracting from the 3D object. The electric blue serves as an action color for the controls.",
      typography_title: 'Typography',
      typography_description: "The 'Space Grotesk' font is used for all text, providing a modern and technical look. The hierarchy is clear to ensure readability.",
      h1_sample: '3D Artist & Developer',
      h2_sample: 'My Fields of Activity',
      h3_sample: '3D Graphics',
      body_sample: 'Combining my passion for 3D creation and my expertise in developing web and interactive applications, I design innovative visual solutions.',
      label_sample: 'View project',
      components_title: 'Components & Interactivity',
      components_description: "The components follow a coherent design logic: structural elements like cards have straight corners for stability, while interactive elements like buttons have rounded corners to invite action.",
      buttons_title: 'Buttons',
      button_primary: 'Primary Button',
      button_secondary: 'Secondary Button',
      button_outline: 'Outline Button',
      button_ghost: 'Ghost Button',
      badges_title: 'Badges',
      badge_default: 'Default Badge',
      badge_secondary: 'Secondary Badge',
      badge_outline: 'Outline Badge',
      badge_sector: 'Sector',
      cards_title: 'Cards',
      card_standard_title: 'Standard Card',
      card_standard_description: 'Used to structure content. Straight corners for a stable and orderly look.',
      card_highlight_title: 'Highlight Card',
      card_highlight_description: 'A border and a primary-colored shadow are used to draw attention.',
      cta_title: "Interested in my design approach?",
      cta_subtitle: "Let's discuss how this rigor and creativity could be applied to your projects.",
      cta_button: "Contact me"
    },
    legal_notice: {
        title: "Legal Notice",
        editor_title: "1. Site Editor",
        editor_name: "Full Name",
        editor_address: "Address",
        editor_email: "Email",
        editor_phone: "Phone",
        hosting_title: "2. Hosting",
        hosting_content: "The site is hosted by [Host Name], whose head office is located at [Host Address] and can be reached at [Host Phone Number].",
        ip_title: "3. Intellectual Property",
        ip_content1: "This entire site is subject to French and international legislation on copyright and intellectual property. All reproduction rights are reserved, including for downloadable documents and iconographic and photographic representations.",
        ip_content2: "The reproduction of all or part of this site on any electronic medium whatsoever is formally prohibited without the express authorization of the publication director.",
        data_title: "4. Personal Data",
        data_content: "The information collected via the contact form is necessary to respond to your request. It is intended solely for Chartrain Donovan and will not be transmitted to third parties. In accordance with the amended \"Informatique et Libertés\" law of January 6, 1978, you have the right to access, rectify, and delete information concerning you.",
    },
    privacy_policy: {
      title: "Privacy Policy",
      introduction_title: "Introduction",
      introduction_content: "This privacy policy aims to inform you about how your personal information is collected and processed on this site. I am committed to protecting your privacy and ensuring that your personal data is treated transparently and securely.",
      collection_title: "Personal Data Collection",
      collection_content: "This site collects data in two ways: data you provide directly and data collected automatically by third-party services.",
      user_data_title: "Data Provided by the User",
      user_data_content: "The only personal data I collect directly is that which you voluntarily provide via the contact form. This data includes:",
      user_data_list: ["Your name", "Your email address", "Your company name (optional)", "Your phone number (optional)", "The content of your message"],
      third_party_data_title: "Data Collected Automatically and by Third Parties",
      third_party_data_content: "To function and provide you with an enriched experience, this site relies on third-party services that may collect data and set cookies:",
      third_party_hosting: "<strong>Hosting (Vercel):</strong> The site is hosted by Vercel. Vercel may collect anonymous analytics data (such as the number of visitors, pages visited, country of origin) to measure site performance and security. This data does not personally identify you.",
      third_party_youtube: "<strong>Embedded Content (YouTube):</strong> The videos embedded on this site are hosted on YouTube. When you load a page containing a video, YouTube (owned by Google) may place cookies on your browser to track your interaction with the video, even if you do not play it. We use YouTube's enhanced privacy mode (`youtube-nocookie.com`) to limit this collection, which in principle is only activated when the video is played.",
      third_party_responsibility: "It is your responsibility to consult the privacy policies of these third-party services for more information.",
      usage_title: "Data Usage",
      usage_content: "The information you provide via the form is used exclusively to:",
      usage_list: ["Respond to your contact requests and questions.", "Communicate with you regarding potential collaboration or project opportunities."],
      usage_share: "Your direct personal data will never be sold, shared, or rented to third parties without your explicit consent.",
      retention_title: "Data Retention Period",
      retention_content: "Your personal data from the contact form is kept for the time necessary to process your request and manage our professional relationship. If no collaboration is initiated, your data will be deleted within a reasonable time.",
      rights_title: "Your Rights",
      rights_content: "In accordance with current regulations (notably the GDPR), you have the following rights regarding your personal data:",
      rights_list: ["Right of access", "Right to rectification", "Right to erasure (right to be forgotten)", "Right to restriction of processing", "Right to data portability"],
      rights_exercise: "To exercise these rights on the data I collect directly, you can contact me at the email address indicated in the legal notice. For data collected by third-party services, you must exercise your rights directly with them.",
      security_title: "Security",
      security_content: "I implement appropriate technical and organizational measures to ensure the security of your personal data and protect it against any loss, destruction, alteration, or unauthorized access.",
      modifications_title: "Changes to the Privacy Policy",
      modifications_content: "I reserve the right to modify this privacy policy at any time. The changes will be published on this page.",
    },
    visualizer: {
      header_back: 'Back to site',
      header_home_breadcrumb: 'Visualizer Space',
      header_library_breadcrumb: 'Library',
      home_title: '3D Visualizer Space',
      home_subtitle: "Welcome to the interactive space. Here, you can manipulate, explore, and examine a selection of my 3D models in detail directly in your browser.",
      home_cta_library: 'Explore the library',
      home_cta_portfolio: 'Back to portfolio',
      home_cta_contact_title: 'Have a project in mind?',
      home_cta_contact_subtitle: "Let's discuss how we could bring your vision to life. I am open to new collaborations.",
      home_cta_contact_button: 'Contact me',
      library_title: 'Model Library',
      library_subtitle: 'Explore, manipulate, and examine all available 3D models.',
      library_loading: 'Loading models...',
      library_empty: 'No 3D models available at the moment.',
      item_card_badge: '3D',
      item_card_cta: 'View model',
      item_detail_loading: 'Loading visualizer...',
      item_detail_not_found: 'Model not found',
      item_detail_not_found_message: 'Could not find information for this model.',
      item_detail_no_model: 'No 3D model available for this item.',
      item_detail_cta_project: 'View project',
      item_detail_cta_library: 'Back to library',
      canvas_loading: 'Loading 3D model...',
      help_close: 'Close help',
      help_title: 'Camera Controls',
      help_mouse_title: 'Mouse',
      help_mouse_rotate: 'Left Click + Drag',
      help_mouse_rotate_desc: 'Rotate',
      help_mouse_pan: 'Right Click + Drag',
      help_mouse_pan_desc: 'Pan',
      help_mouse_zoom: 'Scroll Wheel',
      help_mouse_zoom_desc: 'Zoom',
      help_touch_title: 'Touch',
      help_touch_rotate: '1 Finger + Drag',
      help_touch_rotate_desc: 'Rotate',
      help_touch_zoom: '2 Fingers + Pinch',
      help_touch_zoom_desc: 'Zoom',
      help_touch_pan: '2 Fingers + Drag',
      help_touch_pan_desc: 'Pan',
      help_button_title: 'Show help',
      reset_button_title: 'Reset view',
      autorotate_button_title_pause: 'Pause rotation',
      autorotate_button_title_play: 'Resume rotation',
      fullscreen_button_title_exit: 'Exit full screen',
      fullscreen_button_title_enter: 'Enter full screen',
    },
  },
};
