
export const content = {
  fr: {
    nav: {
      home: 'Accueil',
      portfolio: 'Portfolio',
      about: 'À propos',
      contact: 'Contact',
      visualizer: 'Visualiseur',
    },
    home: {
      title: 'Développeur Web &<br />Artiste 3D',
      subtitle: 'Créateur d\'expériences numériques en Vaucluse et Gard',
      intro_paragraph: 'Basé dans le Vaucluse et mobile dans le Gard, j\'allie mon expertise en <strong>développement web</strong> et ma passion pour la <strong>3D</strong> pour concevoir des solutions innovantes : applications, <strong>configurateurs 3D</strong> et <strong>expériences interactives</strong>.',
      hero_cta: 'Découvrir mes projets',
      three_placeholder: 'Placeholder pour un élément 3D interactif',
      stats: {
          projects: 'Projets réalisés',
          experience: 'Années d\'expérience',
          expertise: 'Domaines d\'expertise',
          technologies: 'Technologies maîtrisées',
      },
      presentation: {
          part1: 'Profil hybride, je fusionne',
          highlight1: 'développement web',
          highlight2: 'développement interactif',
          part2: 'et',
          highlight3: 'design 3D',
          part3: 'pour créer des expériences numériques uniques et engageantes.',
      },
      services: {
          title: 'Mes domaines d\'activité',
          item1: { title: 'Infographie 3D', description: 'En tant qu\'infographiste 3D, je gère la <strong>modélisation</strong>, le <strong>texturing</strong> et l\'<strong>animation</strong> pour l\'architecture, l\'ingénierie et la communication visuelle.' },
          item2: { title: 'Développement 3D Interactif', description: 'Création d\'expériences immersives (<strong>VR, AR, mixte</strong>), de <strong>configurateurs produits</strong> et de visites virtuelles sur <strong>Unity</strong> et <strong>Unreal Engine</strong>.' },
          item3: { title: 'Développement Web', description: 'Conception d\'applications (<strong>React, Next.js</strong>), de backends (<strong>PHP</strong>), de sites <strong>WordPress</strong> et optimisation <strong>SEO</strong>.' },
      },
      showreel: {
          title: 'Donner vie aux idées.',
          subtitle: 'Un aperçu de mon travail en mouvement.',
          cta: 'Voir mes projets',
      },
      skills: {
          title: 'Compétences & outils',
          cta: 'Découvrir toutes mes compétences',
      },
      cta: {
          title: 'Prêt à collaborer ?',
          subtitle: 'Je suis prêt à mettre mes compétences au service de vos projets. Discutons de la manière dont je peux intégrer votre équipe.',
          button: 'Me contacter',
      }
    },
    portfolio: {
      title: 'Mes projets',
      intro: {
        part1: 'Voici une sélection de mes travaux, illustrant l\'étendue de mes compétences : du ',
        highlight1: 'développement web performant',
        part2: ' à la création d\'',
        highlight2: 'applications interactives',
        part3: ' et de ',
        highlight3: 'visuels 3D',
        part4: '.',
      },
      filter_all_projects: 'Tous les projets',
      filter_visualizable_projects: 'Projets 3D Visualisables',
      layout_grid: 'Grille',
      layout_list: 'Liste',
      new_badge: 'Nouveau',
      view_project_cta: 'Voir le projet',
      search_placeholder: 'Rechercher un projet...',
      sort_label: 'Trier par',
      sort_newest: 'Plus récents',
      sort_oldest: 'Plus anciens',
      no_results: 'Aucun projet ne correspond à votre recherche.',
      back_to_portfolio: 'Retour au portfolio',
      interactive_experience_title: 'Expérience interactive',
      visualize_3d_cta: 'Visualiser en 3D',
      gallery_title: 'Galerie',
      other_projects_title: 'Autres projets',
      share_project: 'Partager ce projet :',
      modal_technologies: 'Technologies utilisées',
      modal_close: 'Fermer',
      filters: {
        title: 'Filtrer',
        sector: 'Secteur',
        production: 'Production',
        all: 'Tous',
        all_f: 'Toutes',
        technologies: 'Technologies',
        technologies_label: 'Filtrer par technologie',
        technologies_reset: 'Tout désélectionner',
        sectors: {
          'Infographie 3D': 'Infographiste 3D',
          '3D Temps Réel': '3D Temps Réel',
          'Développement Web': 'Développement Web',
          'Visualisation Architecturale': 'Archi-Viz',
          'Animation 3D / Interactif': 'Animation / Interactif'
        },
        production_types: {
          'Rendu': 'Rendu',
          'Animation': 'Animation',
          'Application': 'Application',
          'Site Web': 'Site Web',
          'Visualisation': 'Visualisation',
          'Animation 3D Interactive': 'Animation Interactive'
        }
      }
    },
    about: {
      title: 'À propos de moi',
      profile_title: 'Profil',
      profile_content: "<p>Je m'appelle Donovan Chartrain, <strong>développeur web</strong> et <strong>infographiste / artiste 3D</strong> passionné par l'interactivité. En recherche active d'un poste dans le Vaucluse et le Gard, j'aime concevoir des expériences qui allient technologie et sens.</p><p>Mon but est de donner vie à des <strong>sites web</strong>, des <strong>applications interactives</strong> ou des <strong>animations 3D</strong> qui marquent les esprits.</p>",
      journey_title: 'Mon parcours',
      journey_content: "<p>Mon chemin a commencé par un Bac Pro en maintenance industrielle, où j'ai appris à comprendre les systèmes techniques et à résoudre des problèmes concrets. C'est cette base solide, ancrée dans le réel, qui m'a permis de développer une approche pragmatique de la création numérique.</p><br/><p>Au fil des années, j'ai travaillé dans des environnements très différents : agence de communication, bureaux d'études, maîtrise d'ouvrage, puis cabinet d'ingénierie. Chacune de ces expériences a forgé une nouvelle facette de mon métier : la <strong>rigueur</strong>, la <strong>créativité</strong>, la <strong>communication</strong>, et surtout, la capacité à <strong>vulgariser des sujets techniques</strong>.</p><br/><p>Aujourd'hui, elles me permettent d'avoir une vision transversale, de passer d'un univers à un autre avec souplesse, et de proposer des solutions complètes, à la fois techniques et humaines.</p>",
      skills_title: 'Compétences',
      experience_title: 'Parcours',
      education_title: 'Formations',
      timeline: [
        {
          type: 'formation',
          role: 'BEP & BAC PRO Maintenance des équipements industriels',
          company: 'Lycée François Rabelais, Fontenay-le-Comte',
          period: '2013 – 2015',
          description: '',
          date: '2013-09-01',
        },
        {
          type: 'experience',
          role: 'Infographiste 3D Junior',
          company: 'COM3D, Pérols (34)',
          period: '2015 – 2016',
          description: '• Rendu photoréaliste et animation marketing.<br/>• Traitement de fichiers CAO pour visualisations 3D.',
          date: '2015-09-01',
        },
        {
          type: 'formation',
          role: 'Modeleur BIM',
          company: 'AFPA Nîmes',
          period: '2020',
          description: '',
          date: '2020-01-01',
        },
        {
          type: 'experience',
          role: 'Dessinateur Projeteur',
          company: 'MB CONCEPTION, Pouzauges (85)',
          period: 'Mars – Mai 2021',
          description: '• Modélisation BIM pour projets architecturaux.',
          date: '2021-03-01',
        },
        {
          type: 'experience',
          role: 'Infographiste 3D / Développeur Unity',
          company: 'POLYNOTES, Meylan (38)',
          period: 'Mai – Octobre 2021',
          description: "• Développement de scènes interactives sous Unity.<br/>• Création de visuels et d'animations 3D.",
          date: '2021-05-01',
        },
        {
          type: 'experience',
          role: 'Infographiste 3D',
          company: 'Grapheau, Saint-Pierre-de-Vassols (84)',
          period: 'Septembre 2022 – Avril 2024',
          description: "• Création d'animations et de visuels 3D.<br/>• Développement d'applications 3D interactives.<br/>• Recherche et développement pour optimiser les outils internes.",
          date: '2022-09-01',
        },
        {
          type: 'formation',
          role: 'Formation SEO/SEA',
          company: 'Financée par Grapheau',
          period: '2024',
          description: '',
          date: '2024-01-01',
        },
        {
          type: 'experience',
          role: 'Développeur Informatique',
          company: 'Grapheau, Saint-Pierre-de-Vassols (84)',
          period: 'Avril 2024 - Juillet 2025',
          description: "• Développement d'outils internes et d'applications interactives.<br/>• Optimisation et structuration des bases de données.<br/>• Intégration de solutions SEO/SEA pour améliorer la visibilité web.",
          date: '2024-04-01',
        },
      ],
      resume_cta: 'Télécharger mon CV',
      resume_section_title: 'Télécharger mon CV',
      resume_section_subtitle: 'Choisissez la version qui correspond le mieux à vos besoins. La version designer est idéale pour une consultation numérique, tandis que la version imprimable est optimisée pour une lecture en noir et blanc.',
      resume_designer_title: 'Version Designer',
      resume_designer_description: 'Une version visuellement riche, parfaite pour une consultation sur écran.',
      resume_printable_title: 'Version Imprimable',
      resume_printable_description: 'Une version sobre et optimisée pour une impression en noir et blanc.',
      resume_download_button: 'Télécharger la version sélectionnée',
      resume_error_title: 'Aucune version sélectionnée',
      resume_error_description: 'Veuillez choisir une version du CV à télécharger.',
    },
    contact: {
      title: 'Contact',
      subtitle: 'Je suis actuellement à la recherche d\'un poste de <strong>développeur web</strong> ou d\'<strong>artiste 3D</strong> dans le Vaucluse, le Gard et leurs alentours. N\'hésitez pas à me contacter pour discuter d\'une future collaboration.',
      form_title: 'Envoyez-moi un message',
      form_name: 'Nom',
      form_name_placeholder: 'Votre nom complet',
      form_email: 'Email',
      email: 'donovan.chartrain@gmail.com',
      form_email_placeholder: 'votre@email.com',
      form_company: 'Nom de l\'entreprise (Optionnel)',
      form_company_placeholder: 'Nom de votre entreprise',
      form_phone: 'Téléphone (Optionnel)',
      phone: '+33 6 43 88 39 60',
      phone_link: '+33643883960',
      form_phone_placeholder: '+33 6 00 00 00 00',
      form_message: 'Message',
      form_message_placeholder: 'Vous pouvez rédiger votre message ici.',
      form_submit: 'Envoyer',
      form_sending: 'Envoi en cours...',
      form_success_title: 'Message envoyé !',
      form_success: 'Merci de m\'avoir contacté. Je vous répondrai dans les plus brefs délais.',
      form_error_title: 'Erreur',
      form_error: 'Une erreur est survenue. Veuillez réessayer.',
      info_title: 'Informations de contact',
      info_email_label: 'Email',
      info_phone_label: 'Téléphone',
      info_location_label: 'Localisation',
      location_text: 'Bédoin (84), France - Mobile sur Vaucluse/Gard',
      social_title: 'Restons connectés',
      social_subtitle: 'Suivez-moi pour voir l\'évolution de mes projets et de nouvelles créations.',
      availability_title: 'Ouvert aux opportunités',
      availability_text: 'Réponse garantie sous 24 heures.',
    },
    validation: {
      name_min: "Le nom doit comporter au moins 2 caractères.",
      email_invalid: "Veuillez saisir une adresse e-mail valide.",
      message_min: "Le message doit comporter au moins 10 caractères.",
    },
    style_guide: {
      title: 'Charte Graphique',
      subtitle: "Les principes, les composants et les styles qui définissent l'identité visuelle de ce portfolio.",
      logo_title: 'Logo',
      logo_description: "Le logo est le point central de l'identité. Il est utilisé dans la navigation principale et le preloader.",
      colors_main_title: 'Palette de Couleurs - Site Principal',
      colors_main_description: "La palette principale est conçue pour être sobre, professionnelle et mettre en valeur le contenu visuel. Elle s'articule autour d'un fond très sombre, rehaussé par une couleur primaire vive et technologique.",
      colors_visualizer_title: 'Palette de Couleurs - Visualiseur 3D',
      colors_visualizer_description: "La palette du visualiseur est plus simple pour ne pas distraire de l'objet 3D. Le bleu électrique sert de couleur d'action pour les contrôles.",
      typography_title: 'Typographie',
      typography_description: "La police 'Space Grotesk' est utilisée pour tous les textes, offrant un aspect moderne et technique. La hiérarchie est claire pour garantir la lisibilité.",
      h1_sample: 'Artiste 3D & Développeur',
      h2_sample: 'Mes Domaines d\'Activité',
      h3_sample: 'Infographie 3D',
      body_sample: 'Alliant ma passion pour la création 3D et mon expertise en développement d\'applications web et interactives, je conçois des solutions visuelles innovantes.',
      label_sample: 'Voir le projet',
      components_title: 'Composants et Interactivité',
      components_description: "Les composants suivent une logique de design cohérente : les éléments structurels comme les cartes ont des coins droits pour la stabilité, tandis que les éléments interactifs comme les boutons ont des coins arrondis pour inviter à l'action.",
      buttons_title: 'Boutons',
      button_primary: 'Bouton Primaire',
      button_secondary: 'Bouton Secondaire',
      button_outline: 'Bouton Contour',
      button_ghost: 'Bouton Fantôme',
      badges_title: 'Badges',
      badge_default: 'Badge Défaut',
      badge_secondary: 'Badge Secondaire',
      badge_outline: 'Badge Contour',
      badge_sector: 'Secteur',
      cards_title: 'Cartes',
      card_standard_title: 'Carte Standard',
      card_standard_description: "Utilisée pour structurer le contenu. Coins droits pour un aspect stable et ordonné.",
      card_highlight_title: 'Carte Mise en Avant',
      card_highlight_description: "Une bordure et une ombre de couleur primaire sont utilisées pour attirer l'attention.",
      cta_title: "Intéressé par mon approche du design ?",
      cta_subtitle: "Discutons de la manière dont cette rigueur et cette créativité pourraient s'appliquer à vos projets.",
      cta_button: "Me contacter"
    },
    legal_notice: {
        title: "Mentions Légales",
        editor_title: "1. Éditeur du site",
        editor_name: "Nom & Prénom",
        editor_address: "Adresse",
        editor_email: "Email",
        editor_phone: "Téléphone",
        hosting_title: "2. Hébergement",
        hosting_content: "<p>Le site est hébergé par Vercel Inc., dont le siège social est situé à 340 S Lemon Ave #4133 Walnut, CA 91789, et joignable à l'adresse mail privacy@vercel.com.</p>",
        ip_title: "3. Propriété intellectuelle",
        ip_content1: "<p>L'ensemble de ce site relève de la législation française et internationale sur le droit d'auteur et la propriété intellectuelle. Tous les droits de reproduction sont réservés, y compris pour les documents téléchargeables et les représentations iconographiques et photographiques.</p>",
        ip_content2: "<p>La reproduction de tout ou partie de ce site sur un support électronique quel qu'il soit est formellement interdite sauf autorisation expresse du directeur de la publication.</p>",
        data_title: "4. Données personnelles",
        data_content: "<p>Les informations recueillies via le formulaire de contact sont nécessaires pour répondre à votre demande. Elles sont destinées uniquement à Chartrain Donovan et ne seront pas transmises à des tiers. Conformément à la loi \"informatique et libertés\" du 6 janvier 1978 modifiée, vous bénéficiez d’un droit d’accès, de rectification et de suppression des informations qui vous concernent.</p>",
    },
    privacy_policy: {
      title: "Politique de Confidentialité",
      introduction_title: "Introduction",
      introduction_content: "<p>Cette politique de confidentialité a pour objectif de vous informer sur la manière dont vos informations personnelles sont collectées et traitées sur ce site. Je m'engage à protéger votre vie privée et à garantir que vos données personnelles sont traitées de manière transparente et sécurisée.</p>",
      collection_title: "Collecte des données personnelles",
      collection_content: "<p>Ce site collecte des données de trois manières : les données que vous me fournissez directement, les données collectées via l'assistant IA, et les données collectées automatiquement par des services tiers.</p>",
      user_data_title: "Données fournies par l'utilisateur",
      user_data_content: "<p>Les données personnelles que je collecte directement sont celles que vous me fournissez volontairement via le formulaire de contact. Ces données incluent :</p>",
      user_data_list: ["<li>Votre nom</li>", "<li>Votre adresse e-mail</li>", "<li>Le nom de votre entreprise (facultatif)</li>", "<li>Votre numéro de téléphone (facultatif)</li>", "<li>Le contenu de votre message</li>"],
      ai_assistant_data_title: "Données de l'Assistant IA",
      ai_assistant_data_content: "<p>L'assistant IA (chatbot) est conçu pour vous aider à naviguer sur le site. Lorsque vous utilisez cette fonctionnalité :</p>",
      ai_assistant_data_list: [
        "<li>Les messages que vous envoyez sont traités pour comprendre votre demande.</li>",
        "<li>Ces messages sont envoyés aux serveurs de Google (Google Generative AI) pour générer une réponse pertinente.</li>",
        "<li>L'historique de votre conversation est conservé dans votre navigateur pendant votre session de navigation mais n'est pas stocké sur nos serveurs. Il est perdu lorsque vous fermez ou rechargez la page.</li>",
        "<li><strong>Important :</strong> Ne saisissez aucune information personnelle sensible (financière, médicale, etc.) dans le chatbot.</li>"
      ],
      third_party_data_title: "Données collectées automatiquement et par des tiers",
      third_party_data_content: "<p>Pour fonctionner et vous offrir une expérience enrichie, ce site s'appuie sur des services tiers qui peuvent collecter des données et déposer des cookies, sous réserve de votre consentement :</p>",
      third_party_hosting: "<strong>Hébergement et Analyse (Vercel) :</strong> Le site est hébergé par Vercel, qui peut collecter des données d'analyse anonymes pour mesurer les performances. Ces données ne sont collectées que si vous acceptez les cookies d'analyse.",
      third_party_youtube: "<strong>Contenu embarqué (YouTube) :</strong> Les vidéos intégrées utilisent le mode de confidentialité avancée de YouTube (`youtube-nocookie.com`) pour limiter la collecte de données avant la lecture de la vidéo.",
      third_party_google: "<strong>Google Tag Manager :</strong> Utilisé pour gérer les balises de script pour l'analyse, mais ne se déclenche que si vous donnez votre consentement aux cookies.",
      third_party_responsibility: "<p>Il est de votre responsabilité de consulter les politiques de confidentialité de ces services tiers pour plus d'informations.</p>",
      usage_title: "Utilisation des données",
      usage_content: "<p>Les informations que vous fournissez sont utilisées exclusivement pour :</p>",
      usage_list: ["<li>Répondre à vos demandes de contact.</li>", "<li>Fournir des réponses pertinentes via l'assistant IA.</li>", "<li>Améliorer le site grâce aux données d'analyse anonymes (si consentement).</li>"],
      usage_share: "<p>Vos données personnelles directes ne seront jamais vendues, partagées ou louées à des tiers sans votre consentement explicite.</p>",
      retention_title: "Durée de conservation des données",
      retention_content: "<p>Vos données personnelles issues du formulaire de contact sont conservées pour la durée nécessaire au traitement de votre demande. Les données de l'assistant IA ne sont pas conservées sur le serveur. Les données d'analyse anonymes sont conservées par Vercel selon leur politique.</p>",
      cookie_policy_title: "Politique d'utilisation des Cookies",
      cookie_what_are_cookies_title: "Qu'est-ce qu'un cookie ?",
      cookie_what_are_cookies_content: "<p>Un cookie est un petit fichier texte stocké sur votre ordinateur ou appareil mobile par votre navigateur web lorsque vous visitez un site. Il permet au site de mémoriser vos actions et préférences.</p>",
      cookie_how_we_use_cookies_title: "Comment utilisons-nous les cookies ?",
      cookie_how_we_use_cookies_content: "<p>Ce site utilise des cookies pour les raisons suivantes :</p>",
      cookie_usage_list: [
        "<li><strong>Cookies strictement nécessaires :</strong> Pour mémoriser votre choix concernant le consentement aux cookies et vos préférences linguistiques.</li>",
        "<li><strong>Cookies d'analyse et de performance (si acceptés) :</strong> Nous utilisons Vercel Analytics et Google Tag Manager pour collecter des informations anonymes afin d'améliorer l'expérience utilisateur. Ces cookies ne sont déposés que si vous donnez votre consentement explicite via la bannière de cookies.</li>",
        "<li><strong>Cookies de tiers (contenu embarqué) :</strong> Des services comme YouTube peuvent déposer leurs propres cookies lorsque vous interagissez avec leur contenu.</li>"
      ],
      cookie_your_choices_title: "Vos choix concernant les cookies",
      cookie_your_choices_content: "<p>Lorsque vous visitez notre site pour la première fois, une bannière s'affiche pour vous demander votre consentement pour l'utilisation de cookies non essentiels. Vous avez le choix d'accepter ou de refuser.</p>",
      cookie_manage_preferences: "<p>Vous pouvez modifier vos préférences à tout moment et retirer votre consentement. Vous pouvez également configurer votre navigateur pour refuser tous les cookies ou pour vous alerter lorsque des cookies sont envoyés.</p>",
      rights_title: "Vos droits",
      security_title: "Sécurité",
      security_content: "<p>Je mets en œuvre les mesures techniques et organisationnelles appropriées pour garantir la sécurité de vos données personnelles et les protéger contre toute perte, destruction, altération ou accès non autorisé.</p>",
      modifications_title: "Modifications de la politique de confidentialité",
      modifications_content: "<p>Je me réserve le droit de modifier cette politique de confidentialité à tout moment. Les modifications seront publiées sur cette page.</p>",
      rights_content: "<p>Conformément à la réglementation en vigueur (notamment le RGPD), vous disposez des droits suivants concernant vos données personnelles :</p>",
      rights_list: ["<li>Droit d'accès</li>", "<li>Droit de rectification</li>", "<li>Droit à l'effacement (droit à l'oubli)</li>", "<li>Droit à la limitation du traitement</li>", "<li>Droit à la portabilité des données</li>"],
      rights_exercise: "<p>Pour exercer ces droits sur les données que je collecte directement, vous pouvez me contacter à l'adresse e-mail indiquée dans les mentions légales. Pour les données collectées par les services tiers, vous devez exercer vos droits directement auprès d'eux.</p>",
    },
    visualizer: {
      header_back: 'Retourner au site',
      header_home_breadcrumb: 'Espace Visualiseur',
      header_library_breadcrumb: 'Bibliothèque',
      home_title: 'Espace Visualiseur 3D',
      home_subtitle: "Bienvenue dans l'espace interactif. Ici, vous pouvez manipuler, explorer et examiner en détail une sélection de mes modèles 3D directement dans votre navigateur.",
      home_cta_library: 'Explorer la bibliothèque',
      home_cta_portfolio: 'Retourner au portfolio',
      home_cta_contact_title: 'Un projet en tête ?',
      home_cta_contact_subtitle: "Discutons de la manière dont nous pourrions concrétiser votre vision. Je suis ouvert à de nouvelles collaborations.",
      home_cta_contact_button: 'Me contacter',
      tech_showcase: {
        title: "Les Coulisses du Visualiseur",
        subtitle: "Comment la 3D et le Web se rencontrent.",
        why_title: "Pourquoi un Visualiseur 3D ?",
        why_content: "Pour aller au-delà des images statiques. Ce visualiseur est une vitrine de mes compétences en <strong>optimisation 3D pour le temps réel</strong>. Chaque modèle est préparé pour être léger et performant, tout en conservant un haut niveau de détail, une compétence essentielle pour les configurateurs de produits, l'immobilier ou les jeux vidéo.",
        how_title: "Comment ça fonctionne ?",
        how_content: "Cette section est bâtie avec <strong>Next.js</strong> et <strong>React</strong>. La scène 3D est rendue via la bibliothèque <strong>@react-three/fiber</strong>, qui permet d'utiliser la puissance de <strong>Three.js</strong> de manière déclarative. Les modèles sont chargés de manière asynchrone pour ne pas bloquer la page, garantissant une expérience fluide."
      },
      library_title: 'Bibliothèque des modèles',
      library_subtitle: 'Explorez, manipulez et examinez tous les modèles 3D disponibles.',
      library_loading: 'Chargement des modèles...',
      library_empty: 'Aucun modèle 3D disponible pour le moment.',
      library_featured_title: 'Modèles à la une',
      library_all_title: 'Tous les modèles',
      item_card_badge: '3D',
      item_card_cta: 'Voir le modèle',
      item_detail_loading: 'Chargement du visualiseur...',
      item_detail_not_found: 'Modèle non trouvé',
      item_detail_not_found_message: 'Impossible de trouver les informations pour ce modèle.',
      item_detail_no_model: 'Aucun modèle 3D disponible pour cet objet.',
      item_detail_cta_project: 'Voir le projet associé',
      item_detail_cta_library: 'Retour à la bibliothèque',
      canvas_loading: 'Chargement du modèle 3D...',
      help_close: "Fermer l'aide",
      help_title: 'Contrôles Caméra',
      help_mouse_title: 'Souris',
      help_mouse_rotate: 'Clic Gauche + Glisser',
      help_mouse_rotate_desc: 'Rotation',
      help_mouse_pan: 'Clic Droit + Glisser',
      help_mouse_pan_desc: 'Pivoter',
      help_mouse_zoom: 'Molette',
      help_mouse_zoom_desc: 'Zoomer',
      help_touch_title: 'Tactile',
      help_touch_rotate: '1 Doigt + Glisser',
      help_touch_rotate_desc: 'Rotation',
      help_touch_zoom: '2 Doigts + Pincer',
      help_touch_zoom_desc: 'Zoomer',
      help_touch_pan: '2 Doigts + Glisser',
      help_touch_pan_desc: 'Pivoter',
      help_button_title: "Afficher l'aide",
      reset_button_title: 'Réinitialiser la vue',
      autorotate_button_title_pause: 'Mettre en pause la rotation',
      autorotate_button_title_play: 'Reprendre la rotation',
      fullscreen_button_title_exit: 'Quitter le plein écran',
      fullscreen_button_title_enter: 'Passer en plein écran',
      tech_details_title: 'Conception & Coulisses',
      tech_details_polycount: 'Nombre de polygones',
      tech_details_materials: 'Nombre de matériaux',
      tech_details_software: 'Logiciels utilisés',
      filters: {
        all: 'Tout voir'
      }
    },
    sitemap: {
        title: 'Plan du site',
        back_to_home: 'Retour à l\'accueil',
        main_pages: 'Pages principales',
        portfolio_projects: 'Projets du Portfolio',
        visualizer_space: 'Espace Visualiseur 3D',
        visualizer_models_subtitle: 'Modèles 3D :',
        legal_info: 'Infos Légales & Plus'
    }
  },
  en: {
    nav: {
      home: 'Home',
      portfolio: 'Portfolio',
      about: 'About',
      contact: 'Contact',
      visualizer: '3D viewer',
    },
    home: {
      title: 'Web Developer &<br />3D Artist',
      subtitle: 'Creator of immersive digital experiences in Vaucluse & Gard, France',
      intro_paragraph: 'Based in the Vaucluse and mobile in the Gard area, I combine my expertise in <strong>web development</strong> and my passion for <strong>3D</strong> to design innovative solutions: applications, <strong>3D configurators</strong>, and <strong>interactive experiences</strong>.',
      hero_cta: 'Discover my projects',
      three_placeholder: 'Placeholder for an interactive 3D element',
       stats: {
          projects: 'Projects completed',
          experience: 'Years of experience',
          expertise: 'Areas of expertise',
          technologies: 'Technologies mastered',
      },
      presentation: {
          part1: 'With a hybrid profile, I merge',
          highlight1: 'web development',
          highlight2: 'interactive development',
          part2: 'and',
          highlight3: '3D design',
          part3: 'to create unique and engaging digital experiences.',
      },
      services: {
          title: 'My fields of activity',
          item1: { title: '3D Graphics', description: 'As a 3D graphic designer, I handle <strong>modeling</strong>, <strong>texturing</strong>, and <strong>animation</strong> for architecture, engineering, and visual communication.' },
          item2: { title: 'Interactive 3D Development', description: 'Creation of immersive experiences (<strong>VR, AR, mixed reality</strong>), <strong>product configurators</strong>, and virtual tours on <strong>Unity</strong> and <strong>Unreal Engine</strong>.' },
          item3: { title: 'Web Development', description: 'Design of applications (<strong>React, Next.js</strong>), backends (<strong>PHP</strong>), <strong>WordPress</strong> sites, and <strong>SEO</strong> optimization.' },
      },
      showreel: {
          title: 'Bringing ideas to life.',
          subtitle: 'A glimpse of my work in motion.',
          cta: 'See my projects',
      },
      skills: {
          title: 'Skills & tools',
          cta: 'Discover all my skills',
      },
      cta: {
          title: 'Ready to collaborate?',
          subtitle: 'I am ready to put my skills at the service of your projects. Let\'s discuss how I can join your team.',
          button: 'Contact me',
      }
    },
    portfolio: {
      title: 'My projects',
      intro: {
        part1: 'Here is a selection of my work, illustrating the breadth of my skills: from ',
        highlight1: 'high-performance web development',
        part2: ' to the creation of ',
        highlight2: 'interactive applications',
        part3: ' and ',
        highlight3: '3D visuals',
        part4: '.',
      },
      filter_all_projects: 'All Projects',
      filter_visualizable_projects: 'Viewable 3D Projects',
      layout_grid: 'Grid',
      layout_list: 'List',
      new_badge: 'New',
      view_project_cta: 'View Project',
      search_placeholder: 'Search for a project...',
      sort_label: 'Sort by',
      sort_newest: 'Newest',
      sort_oldest: 'Oldest',
      no_results: 'No projects match your search.',
      back_to_portfolio: 'Back to portfolio',
      interactive_experience_title: 'Interactive Experience',
      visualize_3d_cta: 'Visualize in 3D',
      gallery_title: 'Gallery',
      other_projects_title: 'Other Projects',
      share_project: 'Share this project:',
      modal_technologies: 'Technologies used',
      modal_close: 'Close',
      filters: {
        title: 'Filter',
        sector: 'Sector',
        production: 'Production',
        all: 'All',
        all_f: 'All',
        technologies: 'Technologies',
        technologies_label: 'Filter by technology',
        technologies_reset: 'Deselect all',
        sectors: {
          'Infographie 3D': '3D Graphic Designer',
          '3D Temps Réel': 'Real-Time 3D',
          'Développement Web': 'Web Development',
          'Visualisation Architecturale': 'Archi-Viz',
          'Animation 3D / Interactif': 'Animation / Interactive'
        },
        production_types: {
          'Rendu': 'Rendering',
          'Animation': 'Animation',
          'Application': 'Application',
          'Site Web': 'Website',
          'Visualisation': 'Visualization',
          'Animation 3D Interactive': 'Interactive Animation'
        }
      }
    },
    about: {
      title: 'About me',
      profile_title: 'Profile',
      profile_content: "<p>My name is Donovan Chartrain, a <strong>web developer</strong> and <strong>3D graphic designer / artist</strong> passionate about interactivity. Actively seeking a position in the Vaucluse and Gard regions, I enjoy designing experiences that blend technology and meaning.</p><p>My goal is to bring to life <strong>websites</strong>, <strong>interactive applications</strong>, or <strong>3D animations</strong> that make a lasting impression.</p>",
      journey_title: 'My Journey',
      journey_content: "<p>My path began with a vocational degree in industrial maintenance, where I learned to understand technical systems and solve concrete problems. It is this solid, reality-based foundation that has allowed me to develop a pragmatic approach to digital creation.</p><br/><p>Over the years, I have worked in very different environments: a communication agency, design offices, project management, and then an engineering firm. Each of these experiences has forged a new facet of my profession: <strong>rigor</strong>, <strong>creativity</strong>, <strong>communication</strong>, and above all, the ability to <strong>simplify technical subjects</strong>.</p><br/><p>Today, they allow me to have a cross-functional vision, to move from one world to another with flexibility, and to offer complete solutions that are both technical and human.</p>",
      skills_title: 'Skills',
      experience_title: 'Journey',
      education_title: 'Education',
      timeline: [
        {
          type: 'formation',
          role: 'Vocational Degree in Industrial Equipment Maintenance',
          company: 'Lycée François Rabelais, Fontenay-le-Comte',
          period: '2013 – 2015',
          description: '',
          date: '2013-09-01',
        },
        {
          type: 'experience',
          role: 'Junior 3D Artist',
          company: 'COM3D, Pérols (34)',
          period: '2015 – 2016',
          description: '• Photorealistic rendering and marketing animation.<br/>• Processing of CAD files for 3D visualizations.',
          date: '2015-09-01',
        },
        {
          type: 'formation',
          role: 'BIM Modeler',
          company: 'AFPA Nîmes',
          period: '2020',
          description: '',
          date: '2020-01-01',
        },
        {
          type: 'experience',
          role: 'Draftsman/Designer',
          company: 'MB CONCEPTION, Pouzauges (85)',
          period: 'March – May 2021',
          description: '• BIM modeling for architectural projects.',
          date: '2021-03-01',
        },
        {
          type: 'experience',
          role: '3D Artist / Unity Developer',
          company: 'POLYNOTES, Meylan (38)',
          period: 'May – October 2021',
          description: "• Development of interactive scenes in Unity.<br/>• Creation of 3D visuals and animations.",
          date: '2021-05-01',
        },
        {
          type: 'experience',
          role: '3D Artist',
          company: 'Grapheau, Saint-Pierre-de-Vassols (84)',
          period: 'September 2022 – April 2024',
          description: "• Creation of 3D animations and visuals.<br/>• Development of interactive 3D applications.<br/>• Research and development to optimize internal tools.",
          date: '2022-09-01',
        },
        {
          type: 'formation',
          role: 'SEO/SEA Training',
          company: 'Funded by Grapheau',
          period: '2024',
          description: '',
          date: '2024-01-01',
        },
        {
          type: 'experience',
          role: 'IT Developer',
          company: 'Grapheau, Saint-Pierre-de-Vassols (84)',
          period: 'April 2024 - July 2025',
          description: "• Development of internal tools and interactive applications.<br/>• Database optimization and structuring.<br/>• Integration of SEO/SEA solutions to improve web visibility.",
          date: '2024-04-01',
        },
      ],
      resume_cta: 'Download my Resume',
      resume_section_title: 'Download my Resume',
      resume_section_subtitle: 'Choose the version that best suits your needs. The designer version is ideal for digital viewing, while the printable version is optimized for black and white reading.',
      resume_designer_title: 'Designer Version',
      resume_designer_description: 'A visually rich version, perfect for on-screen viewing.',
      resume_printable_title: 'Printable Version',
      resume_printable_description: 'A clean version optimized for black and white printing.',
      resume_download_button: 'Download selected version',
      resume_error_title: 'No version selected',
      resume_error_description: 'Please select a CV version to download.',
    },
    contact: {
      title: 'Contact',
      subtitle: 'I am currently seeking new professional opportunities as a <strong>web developer</strong> or <strong>3D artist</strong> in the Vaucluse, Gard, and surrounding areas. Please feel free to contact me to discuss a future collaboration.',
      form_title: 'Send me a message',
      form_name: 'Name',
      form_name_placeholder: 'Your full name',
      form_email: 'Email',
      email: 'donovan.chartrain@gmail.com',
      form_email_placeholder: 'your@email.com',
      form_company: 'Company Name (Optional)',
      form_company_placeholder: 'Your company\'s name',
      form_phone: 'Phone Number (Optional)',
      phone: '+33 6 43 88 39 60',
      phone_link: '+33643883960',
      form_phone_placeholder: '+1 (555) 000-0000',
      form_message: 'Message',
      form_message_placeholder: 'You can write your message here.',
      form_submit: 'Send',
      form_sending: 'Sending...',
      form_success_title: 'Message sent!',
      form_success: 'Thank you for contacting me. I will get back to you as soon as possible.',
      form_error_title: 'Error',
      form_error: 'An error occurred. Please try again.',
      info_title: 'Contact information',
      info_email_label: 'Email',
      info_phone_label: 'Phone',
      info_location_label: 'Location',
      location_text: 'Bédoin (84), France - Mobile in Vaucluse/Gard area',
      social_title: 'Let\'s connect',
      social_subtitle: 'Follow me to see my projects evolve and discover new creations.',
      availability_title: 'Open to opportunities',
      availability_text: 'Guaranteed response within 24 hours.',
    },
    validation: {
      name_min: "Name must be at least 2 characters.",
      email_invalid: "Please enter a valid email address.",
      message_min: "Message must be at least 10 characters.",
    },
    style_guide: {
      title: 'Style Guide',
      subtitle: "The principles, components, and styles that define this portfolio's visual identity.",
      logo_title: 'Logo',
      logo_description: 'The logo is the focal point of the identity. It is used in the main navigation and the preloader.',
      colors_main_title: 'Color Palette - Main Site',
      colors_main_description: 'The main palette is designed to be sober, professional, and to highlight visual content. It is based on a very dark background, enhanced by a bright and technological primary color.',
      colors_visualizer_title: 'Color Palette - 3D Visualizer',
      colors_visualizer_description: "The visualizer's palette is simpler to avoid distracting from the 3D object. The electric blue serves as an action color for the controls.",
      typography_title: 'Typography',
      typography_description: "The 'Space Grotesk' font is used for all text, providing a modern and technical look. The hierarchy is clear to ensure readability.",
      h1_sample: '3D Artist & Developer',
      h2_sample: 'My Fields of Activity',
      h3_sample: '3D Graphics',
      body_sample: 'Combining my passion for 3D creation and my expertise in developing web and interactive applications, I design innovative visual solutions.',
      label_sample: 'View project',
      components_title: 'Components & Interactivity',
      components_description: "The components follow a coherent design logic: structural elements like cards have straight corners for stability, while interactive elements like buttons have rounded corners to invite action.",
      buttons_title: 'Buttons',
      button_primary: 'Primary Button',
      button_secondary: 'Secondary Button',
      button_outline: 'Outline Button',
      button_ghost: 'Ghost Button',
      badges_title: 'Badges',
      badge_default: 'Default Badge',
      badge_secondary: 'Secondary Badge',
      badge_outline: 'Outline Badge',
      badge_sector: 'Sector',
      cards_title: 'Cards',
      card_standard_title: 'Standard Card',
      card_standard_description: 'Used to structure content. Straight corners for a stable and orderly look.',
      card_highlight_title: 'Highlight Card',
      card_highlight_description: 'A border and a primary-colored shadow are used to draw attention.',
      cta_title: "Interested in my design approach?",
      cta_subtitle: "Let's discuss how this rigor and creativity could be applied to your projects.",
      cta_button: "Contact me"
    },
    legal_notice: {
        title: "Legal Notice",
        editor_title: "1. Site Editor",
        editor_name: "Full Name",
        editor_address: "Address",
        editor_email: "Email",
        editor_phone: "Phone",
        hosting_title: "2. Hosting",
        hosting_content: "<p>The site is hosted by Vercel Inc., whose head office is located at 340 S Lemon Ave #4133 Walnut, CA 91789, and can be reached at the email address privacy@vercel.com.</p>",
        ip_title: "3. Intellectual Property",
        ip_content1: "<p>This entire site is subject to French and international legislation on copyright and intellectual property. All reproduction rights are reserved, including for downloadable documents and iconographic and photographic representations.</p>",
        ip_content2: "<p>The reproduction of all or part of this site on any electronic medium whatsoever is formally prohibited without the express authorization of the publication director.</p>",
        data_title: "4. Personal Data",
        data_content: "<p>The information collected via the contact form is necessary to respond to your request. It is intended solely for Chartrain Donovan and will not be transmitted to third parties. In accordance with the amended \"Informatique et Libertés\" law of January 6, 1978, you have the right to access, rectify, and delete information concerning you.</p>",
    },
    privacy_policy: {
      title: "Privacy Policy",
      introduction_title: "Introduction",
      introduction_content: "<p>This privacy policy aims to inform you about how your personal information is collected and processed on this site. I am committed to protecting your privacy and ensuring that your personal data is treated transparently and securely.</p>",
      collection_title: "Personal Data Collection",
      collection_content: "<p>This site collects data in three ways: data you provide directly, data collected via the AI assistant, and data collected automatically by third-party services.</p>",
      user_data_title: "Data Provided by the User",
      user_data_content: "<p>The personal data I collect directly is that which you voluntarily provide via the contact form. This data includes:</p>",
      user_data_list: ["<li>Your name</li>", "<li>Your email address</li>", "<li>Your company name (optional)</li>", "<li>Your phone number (optional)</li>", "<li>The content of your message</li>"],
      ai_assistant_data_title: "AI Assistant Data",
      ai_assistant_data_content: "<p>The AI assistant (chatbot) is designed to help you navigate the site. When you use this feature:</p>",
      ai_assistant_data_list: [
        "<li>The messages you send are processed to understand your request.</li>",
        "<li>These messages are sent to Google's servers (Google Generative AI) to generate a relevant response.</li>",
        "<li>Your conversation history is stored in your browser during your browsing session but is not stored on our servers. It is lost when you close or reload the page.</li>",
        "<li><strong>Important:</strong> Do not enter any sensitive personal information (financial, medical, etc.) in the chatbot.</li>"
      ],
      third_party_data_title: "Data Collected Automatically and by Third Parties",
      third_party_data_content: "<p>To function and provide you with an enriched experience, this site relies on third-party services that may collect data and set cookies, subject to your consent:</p>",
      third_party_hosting: "<strong>Hosting and Analytics (Vercel):</strong> The site is hosted by Vercel, which may collect anonymous analytics data to measure performance. This data is only collected if you accept analytics cookies.",
      third_party_youtube: "<strong>Embedded Content (YouTube):</strong> Embedded videos use YouTube's enhanced privacy mode (`youtube-nocookie.com`) to limit data collection before the video is played.",
      third_party_google: "<strong>Google Tag Manager:</strong> Used to manage script tags for analytics, but only triggers if you consent to cookies.",
      third_party_responsibility: "<p>It is your responsibility to consult the privacy policies of these third-party services for more information.</p>",
      usage_title: "Data Usage",
      usage_content: "<p>The information you provide is used exclusively to:</p>",
      usage_list: ["<li>Respond to your contact requests.</li>", "<li>Provide relevant answers via the AI assistant.</li>", "<li>Improve the site using anonymous analytics data (if consent is given).</li>"],
      usage_share: "<p>Your direct personal data will never be sold, shared, or rented to third parties without your explicit consent.</p>",
      retention_title: "Data Retention Period",
      retention_content: "<p>Your personal data from the contact form is kept for the time necessary to process your request. AI assistant data is not stored on the server. Anonymous analytics data is retained by Vercel according to their policy.</p>",
      cookie_policy_title: "Cookie Policy",
      cookie_what_are_cookies_title: "What are cookies?",
      cookie_what_are_cookies_content: "<p>A cookie is a small text file stored on your computer or mobile device by your web browser when you visit a site. It allows the site to remember your actions and preferences.</p>",
      cookie_how_we_use_cookies_title: "How we use cookies",
      cookie_how_we_use_cookies_content: "<p>This site uses cookies for the following reasons:</p>",
      cookie_usage_list: [
        "<li><strong>Strictly Necessary Cookies:</strong> To remember your choice regarding cookie consent and your language preferences.</li>",
        "<li><strong>Analytics and Performance Cookies (if accepted):</strong> We use Vercel Analytics and Google Tag Manager to collect anonymous information to improve the user experience. These cookies are only placed if you give your explicit consent via the cookie banner.</li>",
        "<li><strong>Third-Party Cookies (embedded content):</strong> Services like YouTube may set their own cookies when you interact with their content.</li>"
      ],
      cookie_your_choices_title: "Your choices regarding cookies",
      cookie_your_choices_content: "<p>When you first visit our site, a banner will appear asking for your consent to use non-essential cookies. You have the choice to accept or decline.</p>",
      cookie_manage_preferences: "<p>You can change your preferences at any time and withdraw your consent. You can also configure your browser to refuse all cookies or to alert you when cookies are being sent.</p>",
      rights_title: "Your Rights",
      security_title: "Security",
      security_content: "<p>I implement appropriate technical and organizational measures to ensure the security of your personal data and protect it against any loss, destruction, alteration, or unauthorized access.</p>",
      modifications_title: "Changes to the Privacy Policy",
      modifications_content: "<p>I reserve the right to modify this privacy policy at any time. The changes will be published on this page.</p>",
      rights_content: "<p>In accordance with current regulations (notably the GDPR), you have the following rights regarding your personal data:</p>",
      rights_list: ["<li>Right of access</li>", "<li>Right to rectification</li>", "<li>Right to erasure (right to be forgotten)</li>", "<li>Right to restriction of processing</li>", "<li>Right to data portability</li>"],
      rights_exercise: "<p>To exercise these rights on the data I collect directly, you can contact me at the email address indicated in the legal notice. For data collected by third-party services, you must exercise your rights directly with them.</p>",
    },
    visualizer: {
      header_back: 'Back to site',
      header_home_breadcrumb: 'Visualizer Space',
      header_library_breadcrumb: 'Library',
      home_title: '3D Visualizer Space',
      home_subtitle: "Welcome to the interactive space. Here, you can manipulate, explore, and examine a selection of my 3D models in detail directly in your browser.",
      home_cta_library: 'Explore the library',
      home_cta_portfolio: 'Back to portfolio',
      home_cta_contact_title: 'Have a project in mind?',
      home_cta_contact_subtitle: "Let's discuss how we could bring your vision to life. I am open to new collaborations.",
      home_cta_contact_button: 'Contact me',
      tech_showcase: {
        title: "Behind the Visualizer",
        subtitle: "Where 3D and Web Development Meet.",
        why_title: "Why a 3D Visualizer?",
        why_content: "To go beyond static images. This visualizer is a showcase of my skills in <strong>real-time 3D optimization</strong>. Each model is prepared to be lightweight and performant while maintaining a high level of detail, a crucial skill for product configurators, real estate, or video games.",
        how_title: "How Does It Work?",
        how_content: "This section is built with <strong>Next.js</strong> and <strong>React</strong>. The 3D scene is rendered using the <strong>@react-three/fiber</strong> library, which allows for the declarative use of <strong>Three.js</strong>'s power. Models are loaded asynchronously to avoid blocking the page, ensuring a smooth experience."
      },
      library_title: 'Model Library',
      library_subtitle: 'Explore, manipulate, and examine all available 3D models.',
      library_loading: 'Loading models...',
      library_empty: 'No 3D models available at the moment.',
      library_featured_title: 'Featured Models',
      library_all_title: 'All Models',
      item_card_badge: '3D',
      item_card_cta: 'View model',
      item_detail_loading: 'Loading visualizer...',
      item_detail_not_found: 'Model not found',
      item_detail_not_found_message: 'Could not find information for this model.',
      item_detail_no_model: 'No 3D model available for this item.',
      item_detail_cta_project: 'View project',
      item_detail_cta_library: 'Back to library',
      canvas_loading: 'Loading 3D model...',
      help_close: 'Close help',
      help_title: 'Camera Controls',
      help_mouse_title: 'Mouse',
      help_mouse_rotate: 'Left Click + Drag',
      help_mouse_rotate_desc: 'Rotate',
      help_mouse_pan: 'Right Click + Drag',
      help_mouse_pan_desc: 'Pan',
      help_mouse_zoom: 'Scroll Wheel',
      help_mouse_zoom_desc: 'Zoom',
      help_touch_title: 'Touch',
      help_touch_rotate: '1 Finger + Drag',
      help_touch_rotate_desc: 'Rotate',
      help_touch_zoom: '2 Fingers + Pinch',
      help_touch_zoom_desc: 'Zoom',
      help_touch_pan: '2 Fingers + Drag',
      help_touch_pan_desc: 'Pan',
      help_button_title: 'Show help',
      reset_button_title: 'Reset view',
      autorotate_button_title_pause: 'Pause rotation',
      autorotate_button_title_play: 'Resume rotation',
      fullscreen_button_title_exit: 'Exit full screen',
      fullscreen_button_title_enter: 'Enter full screen',
      tech_details_title: 'Design & Behind the Scenes',
      tech_details_polycount: 'Polygon Count',
      tech_details_materials: 'Material Count',
      tech_details_software: 'Software Used',
      filters: {
        all: 'View all'
      }
    },
    sitemap: {
        title: 'Sitemap',
        back_to_home: 'Back to home',
        main_pages: 'Main Pages',
        portfolio_projects: 'Portfolio Projects',
        visualizer_space: '3D Visualizer Space',
        visualizer_models_subtitle: '3D Models:',
        legal_info: 'Legal Info & More'
    }
  },
};
